### ISSUE TITLE
upgrade for Flair v3

### ISSUE THREAD

**Issue by weipengyao** [flukadocker/F4D#3]
Dear developers,

First of all, thanks for this docker solution for FLUKA+Flair beginners like me on Macbook with homebrew (not macport).

I can finally play with FLUKA+Flair now.

However, now the Flair has already upgraded to V3, will you also upgrade this repo. for it?

Many thanks!

**Comment by drbokko** [comment]
Dear Weipengyao
thank you for your message. 

I guess this container solution is not needed anymore.

You can use the native MAC OS native version of FLUKA (both the CERN and INFN releases are providing that).
Flair 3 is only compatible with the CERN release, while the  INFN release will still require Flair 2.

Best regards
Vittorio
